version: '3'

services:
  earth_backend:
    build: ./back/
    command: sh -c "PYTHONPATH=/app/back uvicorn main:app --reload --port=8000 --host=0.0.0.0"
    ports:
      - 8000:8000
    volumes:
      - .:/app
    env_file:
      - ./back/earth.env
  mars_backend:
    build: ./back/
    command: sh -c "PYTHONPATH=/app/back uvicorn main:app --reload --port=8001 --host=0.0.0.0"
    ports:
      - 8001:8001
    volumes:
      - .:/app
    env_file:
      - ./back/mars.env